# Generated by Django 4.0.3 on 2023-11-05 04:12

from django.db import migrations, models
import django.db.models.deletion
import toolkit.models
import toolkit.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolkitMainCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToolkitSubCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Toolkits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to=toolkit.models.toolkits_thumbnail_image_upload_path, validators=[toolkit.validator.validate_image_file_extension])),
                ('download_file', models.FileField(blank=True, null=True, upload_to=toolkit.models.toolkits_download_file_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField()),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkits_maincategory', to='toolkit.toolkitmaincategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkits_subcategory', to='toolkit.toolkitsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ToolkitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=toolkit.models.toolkits_image_upload_path, validators=[toolkit.validator.validate_image_file_extension])),
                ('toolkits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkitimage_toolkit', to='toolkit.toolkits')),
            ],
        ),
    ]
