# Generated by Django 4.0.3 on 2023-12-14 06:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import toolkit.models
import toolkit.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('alt', models.TextField(blank=True)),
                ('keyword', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('benefit', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=toolkit.models.toolkit_thumbnail_image_upload_path, validators=[toolkit.validator.validate_image_file_extension])),
                ('squareImage', models.ImageField(blank=True, null=True, upload_to=toolkit.models.toolkit_square_image_upload_path, validators=[toolkit.validator.validate_image_file_extension])),
                ('file', models.FileField(blank=True, null=True, upload_to=toolkit.models.toolkit_download_file_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToolkitMainCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToolkitSubCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToolkitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=toolkit.models.toolkit_image_upload_path, validators=[toolkit.validator.validate_image_file_extension])),
                ('toolkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkitimage_toolkit', to='toolkit.toolkit')),
            ],
        ),
        migrations.AddField(
            model_name='toolkit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_type', to='toolkit.toolkitmaincategory'),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_type2', to='toolkit.toolkitsubcategory'),
        ),
    ]
