# Generated by Django 4.0.3 on 2023-09-28 05:12

from django.db import migrations, models
import toolkit.models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkit',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to=toolkit.models.toolkit_download_file_upload_path),
        ),
    ]
